### PR TITLE
fix: Update bot token regex

### LINKED ISSUE #72: bug: Bot token validation seems to be outdated
Here is the error message I received when starting the bot (don't worry, I just invalidated the token).

```
[Error [ValidationError]: "token" with value "OTc0XzcyXjExMDAxMXUyNxU1.GxrXqy.Udj017Gx47NXXH3xgXXVTnXXTjFxcjzTBOZ1Yw" fails to match the required pattern: /^[\w-]{24}\.[\w-]{6}\.[\w-]{27}$/] {
  _original: {
    token: 'OTc0XzcyXjExMDAxMXUyNxU1.GxrXqy.Udj017Gx47NXXH3xgXXVTnXXTjFxcjzTBOZ1Yw',
    devServer: '974371872886124544',
    intents: []
  },
  details: [
    {
      message: '"token" with value "OTc0XzcyXjExMDAxMXUyNxU1.GxrXqy.Udj017Gx47NXXH3xgXXVTnXXTjFxcjzTBOZ1Yw" fails to match the required pattern: /^[\\w-]{24}\\.[\\w-]{6}\\.[\\w-]{27}$/',
      path: [ 'token' ],
      type: 'string.pattern.base',
      context: {
        name: undefined,
        regex: /^[\w-]{24}\.[\w-]{6}\.[\w-]{27}$/,
        value: 'OTc0XzcyXjExMDAxMXUyNxU1.GxrXqy.Udj017Gx47NXXH3xgXXVTnXXTjFxcjzTBOZ1Yw',
        label: 'token',
        key: 'token'
      }
    }
  ]
}
```

### PR DESCRIPTION
**Pull request by lostdesign**
I will try to write a test for it and maybe move the token validation into its own function so it's testable. Also going to research this change, when it occurred and why.

fixes #72

### CODE REVIEW

**Comment by the94air** [comment]
@lostdesign I think this might bring some backward compatibility issues, the validation should support both old and new regex (in case discord changed their way of generating these tokens) old users will have to regenerate their tokens to use this package further :thinking:

**Comment by lostdesign** [comment]
> @lostdesign I think this might bring some backward compatibility issues, the validation should support both old and new regex (in case discord changed their way of generating these tokens) old users will have to regenerate their tokens to use this package further :thinking:

I think that should be desired. If the schema of a token changed, it is best to change it asap anyways. So I consider it a win if the bot helps with that.

**Comment by Choooks22** [comment]
Best course would probably to just remove the regex entirely, [this part](https://github.com/chookscord/framework/blob/main/packages/cli/src/lib/token-id.ts) should already break if the user provided an actually invalid format, not if the signatures chaged.

**Review by Choooks22 — CHANGES_REQUESTED** [review]
Just remove the entire pattern entirely, I've no clue why I put the test in the first place since it's up to the user to provide an actual valid token.

**Pull request merged**
